package com.rightpath.entity;

import java.time.LocalDateTime;
import java.util.Set;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing the OTP (One-Time Password) details. This class
 * maps to the "OTP" table in the database and stores information related to OTP
 * generation and validation.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "OTP")
public class Otp {
	/**
	 * Unique identifier for each OTP record. Auto-generated by the database.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	private String email;// Email address associated with the OTP.
	private String mobile; 
	private String otp; // The actual OTP code
	private LocalDateTime expirationTime; // Expiration time of the OTP
}
