---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rightpath-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rightpath-app-backend
  template:
    metadata:
      labels:
        app: rightpath-app-backend
    spec:
      imagePullSecrets:
      - name: acr-secret
      hostAliases:
       - ip: "10.224.250.250"
         hostnames:
         - "mysql-server"
         - "db.rightpath.local"
         - "rp-mysql-3.mysql.database.azure.com"
         - "privatelink.mysql.database.azure.com"
       - ip: "4.187.178.140"
         hostnames:
         - "apis.rightpath.com"
         - "labs.rightpath.com"         

      containers:
      - name: rightpath-app-backend
        image: rprighpathacr1.azurecr.io/rightpath-app-backend:43
        command: ["java", "-jar", "rightpath.jar", "--spring.config.location=/etc/config/application.properties"]
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: backend-config-volume
          mountPath: /etc/config/application.properties
          subPath: application.properties
        env:
        # MySQL Configuration
        - name: MYSQL_HOST
          value: "10.224.250.250"
        - name: MYSQL_PORT
          value: "3306"          
                 
      volumes:
      - name: backend-config-volume
        configMap:
          name: backend-config