package com.rightpath.enums;

public enum EmailType {
	
	 APPLICATION_SUCCESS,
	    ACKNOWLEDGEMENT,
	    ACKNOWLEDGEMENT_CONFIRMATION,
	    RECONFIRMATION,
	    REJECTION,
	    WRITTEN_TEST_SUCCESS,
	    WRITTEN_TEST_FAILURE,
	    SHORTLIST_NOTIFICATION,
	    EXAM_SCHEDULE,
	    OTP,
	    PASSWORD_UPDATED,
	    EXAM_SUBMISSION,
	    CODING_EXAM_SUBMISSION,
	    REGISTRATION_SUCCESS

}
